#!/bin/sh

# This script creates Hugo site at the cwd

hugo new site .

if git rev-parse --git-dir > /dev/null 2>&1; then
    # This is a valid git repository (but the current working directory may not
    # be the top level.  Check the output of the git rev-parse command if you
    # care)
    :  # pass
else
    echo "Please create a git repo first."
    exit
fi


# download theme
cd themes
git submodule add https://github.com/tkngch/vienna-minimal
mkdir vienna-minimal/archetypes

# go back to the site root
cd ..

# edit config.toml
echo 'baseurl = "http://localhost"
languageCode = "en-gb"
title = "Project Title"
theme = "vienna-minimal"

# Copyright notice. This is displayer in the footer.
copyright = "&copy; 2016 Takao Noguchi. Creative Commons Attribution 4.0 International License."

PygmentsCodeFences = true
pygmentsStyle  = "lovelace"

[author]
    name = "Takao Noguchi"

[params]
    # Short subtitle/tagline. This is displayed in the header.
    subtitle = "Documentation and Note"
' > config.toml

# create handy scripts
echo '#/bin/sh
now=`date +"%Y-%m-%d-%H-%M"`
filename="${now}.md"
hugo new ${filename}
vim ./content/${filename}
' > addContent.sh
chmod +x addContent.sh

echo '#/bin/sh
hugo server -D
' > startServer.sh
chmod +x startServer.sh
