#!/bin/sh

# EXE=evince
# evince "$@" 2> /dev/null &

# for file in "$@"; do
#     if [[ $file =~ \.pdf$ ]];
#     then echo "Opening" "$file";
#          "$EXE" "$file" 2> /dev/null &
#     fi
# done


file=$(realpath "${1}")
dir=$(dirname "${file}")

# NOTE (2017-11): it is better to whitelist only the file, not the dir, but firejail does not accept special characters for whitelist, so it fails when the file name contains a bracket. Maybe fixed in the future.

firejail --caps.drop=all --disable-mnt --noroot --private-tmp --quiet --net=none --seccomp --whitelist=${dir} evince "${file}"
