#!/bin/sh
# Open terminal emulator.
#
# If a symlink "st" is in ${HOME}/bin, this "st" is executed.
# Otherwise, /usr/bin/urxvt is called.

if [ -L ${HOME}/bin/st ]; then
    # suckless simple terminal
    export GTK_IM_MODULE=fcitx
    export QT_IM_MODULE=fcitx
    export XMODIFIERS=@im=fcitx
    ${HOME}/bin/st 2> /dev/null &
else
    # URXVT
    xrdb -merge ${HOME}/.Xresources
    /usr/bin/urxvt 2> /dev/null &
fi

# GNOME-TERMINAL
# gnome-terminal 2> /dev/null &

# xfce4-terminal
# xfce4-terminal 2> /dev/null &
