#!/bin/sh

if [ -x ${HOME}/bin/st ]; then
    # suckless simple terminal
    ${HOME}/bin/st 2> /dev/null &
else
    # URXVT
    xrdb -merge ${HOME}/.Xresources
    /usr/bin/urxvt 2> /dev/null &
fi

# GNOME-TERMINAL
# gnome-terminal 2> /dev/null &

# xfce4-terminal
# xfce4-terminal 2> /dev/null &
