#!/bin/sh
# xset_status
#
# Set the name of the root window, to show the basic system status.
# This script is intended to be used with dwm.
#
# Usage: xset_status
#

print_network_device() {
    # print the connected device type.
    nmcli device | awk '{if ($3 == "connected") { print $2" " }}'
}

print_fcitx_status() {
    # print "fcitx" if fcitx is installed and active.
    test $(command -v fcitx-remote) && test $(fcitx-remote) -eq 2 && echo "fcitx "
}

print_battery_status() {
    # print remaining battery in percentage
    battery_info_files=$(ls /sys/class/power_supply/*/capacity | grep "BAT")
    test ${battery_info_files} && cat ${battery_info_files} | awk '{ sum += $1 } END { print sum"% " }'
}

print_datetime() {
    # date
    date "+%a %d %b - %H:%M"
}

while true
do
    xsetroot -name " $(print_fcitx_status)$(print_network_device)$(print_battery_status) $(print_datetime)"
    sleep 0.5
done
